<div id="breadcrumb">
    <a href="<?php echo $this->baseUrl(); ?>/admin/">Admin Home</a> &gt;
    <a href="<?php echo $this->baseUrl(); ?>/admin/modules">Modules</a> &gt;
    <a href="<?php echo $this->baseUrl(); ?>/admin/modules/edit/id/<?php echo $this->page->module_id; ?>">Edit Module</a> &gt;
    Delete Question
</div>

<h1>Delete Question</h1>

Are you sure you want to delete this question:

<p>
    <?php echo $this->question->text; ?>
</p>

<form method="post">
    <input type="submit" id="confirm" value="Yes" name="confirm">
    <input type="submit" id="cancel" value="No" name="cancel">
</form>