<h1>User Admin</h1>

<table width="100%" cellspacing="0" cellpadding="0">
    <thead>
        <tr>
            <th>Username</th>
            <th>Name</th>
            <th>Status</th>
            <th>Admin</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->users as $user): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl(); ?>/admin/user/edit/id/<?php echo $user->id?>"><?php echo $user->username; ?></a></td>
            <td><?php echo $user->real_name; ?></td>
            <td align="center"><?php echo ($user->active ? 'Active' : 'Inactive'); ?></td>
            <td align="center"><?php echo ($user->admin ? 'Yes' : 'No'); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" align="right"><a href="<?php echo $this->baseUrl(); ?>/admin/user/add">Add New User</a></td>
        </tr>
    </tfoot>
</table>