<h1>Module Already Completed</h1>

<p>
    This module has already been completed. You can attempt to take it again, but this
    will remove any previous test records, including if you have passed this module.
</p>

<p>
    Are you sure you want to do this module again?
</p>

<form method="post">
    <input type="submit" value="Yes" name="confirm" id="confirm">
    <input type="submit" value="No" name="cancel" id="cancel">
</form>

