<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
       var config = {
		toolbar: [
                    ['Source','-','Save','NewPage','Preview','-','Templates'],
                    ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print', 'SpellChecker', 'Scayt'],
                    ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
                    ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
                    ['BidiLtr', 'BidiRtl'],
                    '/',
                    ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
                    ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
                    ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
                    ['Link','Unlink','Anchor'],
                    ['Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'],
                    '/',
                    ['Styles','Format','Font','FontSize'],
                    ['TextColor','BGColor'],
                    ['Maximize', 'ShowBlocks','-','About']
                ],
                filebrowserBrowseUrl:'<?php echo $this->baseUrl(); ?>/admin/file/browse',
                filebrowserUploadUrl:'<?php echo $this->baseUrl(); ?>/admin/file/upload',
	};

	// Initialize the editor.
	// Callback function can be passed and executed after full instance creation.
	$('#text').ckeditor(config);

    });
</script>

<h1>Edit '<?php echo $this->page->title; ?>'</h1>

<div>
    <?php echo $this->message; ?>
</div>

<?php echo $this->form; ?>