<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">
    function getUrlParam(paramName)
    {
        var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i') ;
        var match = window.location.search.match(reParam) ;

        return (match && match.length > 1) ? match[1] : '' ;
    }


    function sendImage(url) {
        var funcNum = getUrlParam('CKEditorFuncNum');
        window.opener.CKEDITOR.tools.callFunction(funcNum, url);
        window.close();
    }
</script>

<h1>Select a File</h1>

<?php if(count($this->files)): ?>
    <?php foreach($this->files as $file): ?>
        <?php if($file->getFilename() !== '.' && $file->getFilename() !== '..'): ?>
            <a href="#" onClick="sendImage('<?php echo $this->baseUrl();?>/images/uploaded/<?php echo $file."<br>"; ?>')">
                <img src="<?php echo $this->baseUrl();?>/images/uploaded/<?php echo $file."<br>"; ?>">
            </a>
        <?php endif; ?>
    <?php endforeach; ?>
<?php else: ?>
There are no uploaded images.
<?php endif; ?>