<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
       var config = {
		toolbar:
		[
			['Bold', 'Italic', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink'],
			['UIColor']
		]
	};

	// Initialize the editor.
	// Callback function can be passed and executed after full instance creation.
	$('#text').ckeditor(config);

    });
</script>

<h1>Create New Page</h1>

<div>
    <?php echo $this->message; ?>
</div>

<?php echo $this->form; ?>