<div id="breadcrumb">
    <a href="<?php echo $this->baseUrl(); ?>/admin/">Admin Home</a> &gt;
    <a href="<?php echo $this->baseUrl(); ?>/admin/modules">Modules</a> &gt;
    <a href="<?php echo $this->baseUrl(); ?>/admin/modules/edit/id/<?php echo $this->module_id; ?>">Edit Module</a> &gt;
    Add New Question
</div>

<h1>Add New Question</h1>

<div>
    <?php echo $this->message; ?>
</div>

<?php echo $this->form; ?>