<h1>Edit Module '<?php echo $this->module->name; ?>'</h1>

<h2>Lesson Plan</h2>
<ul>
<?php foreach($this->module->Pages as $page): ?>
    <li><a href="/admin/modules/editpage/page/<?php echo $page->id; ?>"><?php echo $page->title; ?></a></li>
<?php endforeach; ?>
    <li><a href="/admin/modules/addpage/mod/<?php echo $this->module->id;?>">Add New Page</a></li>
</ul>

<h2>Questions</h2>
<ul>
<?php foreach($this->module->Questions as $question): ?>
    <li><a href="/admin/modules/editquestion/question/<?php echo $question->id; ?>"><?php echo $question->text; ?></a></li>
<?php endforeach; ?>
    <li><a href="/admin/modules/addquestion/mod/<?php echo $this->module->id;?>">Add New Question</a></li>
</ul>