<div id="breadcrumb">
    <a href="<?php echo $this->baseUrl(); ?>/admin/">Admin Home</a> &gt;
    Modules
</div>

<h1>Modules Admin</h1>

<table cellspacing="0" width="100%" cellpadding="5">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th width="100px">Available</th>
            <th width="100px">Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->modules as $module): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl(); ?>/admin/modules/edit/id/<?php echo $module->id; ?>"><?php echo $module->name; ?></a></td>
            <td><?php echo $module->description; ?></td>
            <td><?php echo date('m-d-Y', strtotime($module->date_available)); ?></td>
            <td align="center"><a href="<?php echo $this->baseUrl(); ?>/admin/modules/delete/id/<?php echo $module->id; ?>">Delete</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" align="right"><a href="<?php echo $this->baseUrl(); ?>/admin/modules/add">Add New Module</a></td>
        </tr>
    </tfoot>
</table>