<html>
    <head>
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/grid.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/start/jquery-ui-1.8.7.custom.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/ayl.css" />

        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.4.4.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.8.7.custom.min.js"></script>
    </head>

    <body>
        <div class="container_12">
            <div class="grid_12" id="header">
                <div class="grid_5 alpha">
                    <h1>Are You Listening?</h1>
                </div>

                <div class="grid_7 omega" id="main-nav">
                    <ul>
                        <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/auth/index/logout">Log Out</a></li>
                        <li><a href="<?php echo $this->baseUrl(); ?>/admin">Admin</a></li>
                    </ul>
                </div>
            </div>

            <div class="clear"></div>

            <div class="grid_12" id="content">
                <?php echo $this->layout()->content; ?>
            </div>

            <div class="clear"></div>

            <div class="grid_12" id="footer">
                AYL &copy 2010 Chris Tankersley
            </div>
        </div>
    </body>
</html>